// lib/core/database/seeding/country_seed_data.dart
//
// Canonical offline country reference dataset for MARJIY.
//
// Source/version: ISO 3166-1 alpha-2 "officially assigned" code elements.
// This module mirrors the current officially assigned ISO 3166-1 alpha-2 list
// (249 entries) as neutral application reference metadata. Codes are stored in
// lowercase to match the database key convention. English values use the ISO
// 3166 English short names; Arabic values are standard Arabic display names.
//
// Review date: 2026-06-07. Dataset reviewed against the ISO 3166-1 officially
// assigned alpha-2 set. Entries are neutral catalog reference data only.
//
// Rules enforced by this module:
// - No runtime fetching or network dependency; the list is compiled in.
// - No historical, withdrawn, transitional-reserved, or user-assigned codes
//   (e.g. no `XK`). Only currently officially assigned alpha-2 entries.
// - No phone calling codes are used as identifiers.
// - The State of Palestine uses key `ps`, Arabic `دولة فلسطين`, English
//   `State of Palestine`.

/// A single canonical country reference entry: lowercase ISO 3166-1 alpha-2
/// [key] plus Arabic and English display names.
typedef CountrySeed = ({String key, String nameAr, String nameEn});

/// The complete officially assigned ISO 3166-1 alpha-2 dataset (249 entries),
/// authored in alphabetical key order for straightforward completeness review.
///
/// Use [orderedCountrySeedData] to obtain the seed/display ordering (Palestine
/// pinned first, then the remaining entries by English display name).
const List<CountrySeed> kCountrySeedData = [
  (key: 'ad', nameAr: 'أندورا', nameEn: 'Andorra'),
  (
    key: 'ae',
    nameAr: 'الإمارات العربية المتحدة',
    nameEn: 'United Arab Emirates',
  ),
  (key: 'af', nameAr: 'أفغانستان', nameEn: 'Afghanistan'),
  (key: 'ag', nameAr: 'أنتيغوا وباربودا', nameEn: 'Antigua and Barbuda'),
  (key: 'ai', nameAr: 'أنغيلا', nameEn: 'Anguilla'),
  (key: 'al', nameAr: 'ألبانيا', nameEn: 'Albania'),
  (key: 'am', nameAr: 'أرمينيا', nameEn: 'Armenia'),
  (key: 'ao', nameAr: 'أنغولا', nameEn: 'Angola'),
  (key: 'aq', nameAr: 'القارة القطبية الجنوبية', nameEn: 'Antarctica'),
  (key: 'ar', nameAr: 'الأرجنتين', nameEn: 'Argentina'),
  (key: 'as', nameAr: 'ساموا الأمريكية', nameEn: 'American Samoa'),
  (key: 'at', nameAr: 'النمسا', nameEn: 'Austria'),
  (key: 'au', nameAr: 'أستراليا', nameEn: 'Australia'),
  (key: 'aw', nameAr: 'أروبا', nameEn: 'Aruba'),
  (key: 'ax', nameAr: 'جزر آلاند', nameEn: 'Åland Islands'),
  (key: 'az', nameAr: 'أذربيجان', nameEn: 'Azerbaijan'),
  (key: 'ba', nameAr: 'البوسنة والهرسك', nameEn: 'Bosnia and Herzegovina'),
  (key: 'bb', nameAr: 'بربادوس', nameEn: 'Barbados'),
  (key: 'bd', nameAr: 'بنغلاديش', nameEn: 'Bangladesh'),
  (key: 'be', nameAr: 'بلجيكا', nameEn: 'Belgium'),
  (key: 'bf', nameAr: 'بوركينا فاسو', nameEn: 'Burkina Faso'),
  (key: 'bg', nameAr: 'بلغاريا', nameEn: 'Bulgaria'),
  (key: 'bh', nameAr: 'البحرين', nameEn: 'Bahrain'),
  (key: 'bi', nameAr: 'بوروندي', nameEn: 'Burundi'),
  (key: 'bj', nameAr: 'بنين', nameEn: 'Benin'),
  (key: 'bl', nameAr: 'سان بارتيلمي', nameEn: 'Saint Barthélemy'),
  (key: 'bm', nameAr: 'برمودا', nameEn: 'Bermuda'),
  (key: 'bn', nameAr: 'بروناي', nameEn: 'Brunei Darussalam'),
  (key: 'bo', nameAr: 'بوليفيا', nameEn: 'Bolivia (Plurinational State of)'),
  (
    key: 'bq',
    nameAr: 'بونير وسينت أوستاتيوس وسابا',
    nameEn: 'Bonaire, Sint Eustatius and Saba',
  ),
  (key: 'br', nameAr: 'البرازيل', nameEn: 'Brazil'),
  (key: 'bs', nameAr: 'جزر البهاما', nameEn: 'Bahamas'),
  (key: 'bt', nameAr: 'بوتان', nameEn: 'Bhutan'),
  (key: 'bv', nameAr: 'جزيرة بوفيه', nameEn: 'Bouvet Island'),
  (key: 'bw', nameAr: 'بوتسوانا', nameEn: 'Botswana'),
  (key: 'by', nameAr: 'بيلاروسيا', nameEn: 'Belarus'),
  (key: 'bz', nameAr: 'بليز', nameEn: 'Belize'),
  (key: 'ca', nameAr: 'كندا', nameEn: 'Canada'),
  (key: 'cc', nameAr: 'جزر كوكوس (كيلينغ)', nameEn: 'Cocos (Keeling) Islands'),
  (
    key: 'cd',
    nameAr: 'جمهورية الكونغو الديمقراطية',
    nameEn: 'Congo, Democratic Republic of the',
  ),
  (
    key: 'cf',
    nameAr: 'جمهورية أفريقيا الوسطى',
    nameEn: 'Central African Republic',
  ),
  (key: 'cg', nameAr: 'الكونغو', nameEn: 'Congo'),
  (key: 'ch', nameAr: 'سويسرا', nameEn: 'Switzerland'),
  (key: 'ci', nameAr: 'ساحل العاج', nameEn: "Côte d'Ivoire"),
  (key: 'ck', nameAr: 'جزر كوك', nameEn: 'Cook Islands'),
  (key: 'cl', nameAr: 'تشيلي', nameEn: 'Chile'),
  (key: 'cm', nameAr: 'الكاميرون', nameEn: 'Cameroon'),
  (key: 'cn', nameAr: 'الصين', nameEn: 'China'),
  (key: 'co', nameAr: 'كولومبيا', nameEn: 'Colombia'),
  (key: 'cr', nameAr: 'كوستاريكا', nameEn: 'Costa Rica'),
  (key: 'cu', nameAr: 'كوبا', nameEn: 'Cuba'),
  (key: 'cv', nameAr: 'الرأس الأخضر', nameEn: 'Cabo Verde'),
  (key: 'cw', nameAr: 'كوراساو', nameEn: 'Curaçao'),
  (key: 'cx', nameAr: 'جزيرة الكريسماس', nameEn: 'Christmas Island'),
  (key: 'cy', nameAr: 'قبرص', nameEn: 'Cyprus'),
  (key: 'cz', nameAr: 'التشيك', nameEn: 'Czechia'),
  (key: 'de', nameAr: 'ألمانيا', nameEn: 'Germany'),
  (key: 'dj', nameAr: 'جيبوتي', nameEn: 'Djibouti'),
  (key: 'dk', nameAr: 'الدنمارك', nameEn: 'Denmark'),
  (key: 'dm', nameAr: 'دومينيكا', nameEn: 'Dominica'),
  (key: 'do', nameAr: 'جمهورية الدومينيكان', nameEn: 'Dominican Republic'),
  (key: 'dz', nameAr: 'الجزائر', nameEn: 'Algeria'),
  (key: 'ec', nameAr: 'الإكوادور', nameEn: 'Ecuador'),
  (key: 'ee', nameAr: 'إستونيا', nameEn: 'Estonia'),
  (key: 'eg', nameAr: 'مصر', nameEn: 'Egypt'),
  (key: 'eh', nameAr: 'الصحراء الغربية', nameEn: 'Western Sahara'),
  (key: 'er', nameAr: 'إريتريا', nameEn: 'Eritrea'),
  (key: 'es', nameAr: 'إسبانيا', nameEn: 'Spain'),
  (key: 'et', nameAr: 'إثيوبيا', nameEn: 'Ethiopia'),
  (key: 'fi', nameAr: 'فنلندا', nameEn: 'Finland'),
  (key: 'fj', nameAr: 'فيجي', nameEn: 'Fiji'),
  (key: 'fk', nameAr: 'جزر فوكلاند', nameEn: 'Falkland Islands (Malvinas)'),
  (key: 'fm', nameAr: 'ميكرونيزيا', nameEn: 'Micronesia (Federated States of)'),
  (key: 'fo', nameAr: 'جزر فارو', nameEn: 'Faroe Islands'),
  (key: 'fr', nameAr: 'فرنسا', nameEn: 'France'),
  (key: 'ga', nameAr: 'الغابون', nameEn: 'Gabon'),
  (
    key: 'gb',
    nameAr: 'المملكة المتحدة',
    nameEn: 'United Kingdom of Great Britain and Northern Ireland',
  ),
  (key: 'gd', nameAr: 'غرينادا', nameEn: 'Grenada'),
  (key: 'ge', nameAr: 'جورجيا', nameEn: 'Georgia'),
  (key: 'gf', nameAr: 'غويانا الفرنسية', nameEn: 'French Guiana'),
  (key: 'gg', nameAr: 'غيرنزي', nameEn: 'Guernsey'),
  (key: 'gh', nameAr: 'غانا', nameEn: 'Ghana'),
  (key: 'gi', nameAr: 'جبل طارق', nameEn: 'Gibraltar'),
  (key: 'gl', nameAr: 'غرينلاند', nameEn: 'Greenland'),
  (key: 'gm', nameAr: 'غامبيا', nameEn: 'Gambia'),
  (key: 'gn', nameAr: 'غينيا', nameEn: 'Guinea'),
  (key: 'gp', nameAr: 'غوادلوب', nameEn: 'Guadeloupe'),
  (key: 'gq', nameAr: 'غينيا الاستوائية', nameEn: 'Equatorial Guinea'),
  (key: 'gr', nameAr: 'اليونان', nameEn: 'Greece'),
  (
    key: 'gs',
    nameAr: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
    nameEn: 'South Georgia and the South Sandwich Islands',
  ),
  (key: 'gt', nameAr: 'غواتيمالا', nameEn: 'Guatemala'),
  (key: 'gu', nameAr: 'غوام', nameEn: 'Guam'),
  (key: 'gw', nameAr: 'غينيا بيساو', nameEn: 'Guinea-Bissau'),
  (key: 'gy', nameAr: 'غيانا', nameEn: 'Guyana'),
  (key: 'hk', nameAr: 'هونغ كونغ', nameEn: 'Hong Kong'),
  (
    key: 'hm',
    nameAr: 'جزيرة هيرد وجزر ماكدونالد',
    nameEn: 'Heard Island and McDonald Islands',
  ),
  (key: 'hn', nameAr: 'هندوراس', nameEn: 'Honduras'),
  (key: 'hr', nameAr: 'كرواتيا', nameEn: 'Croatia'),
  (key: 'ht', nameAr: 'هايتي', nameEn: 'Haiti'),
  (key: 'hu', nameAr: 'المجر', nameEn: 'Hungary'),
  (key: 'id', nameAr: 'إندونيسيا', nameEn: 'Indonesia'),
  (key: 'ie', nameAr: 'أيرلندا', nameEn: 'Ireland'),
  (key: 'il', nameAr: 'إسرائيل', nameEn: 'Israel'),
  (key: 'im', nameAr: 'جزيرة مان', nameEn: 'Isle of Man'),
  (key: 'in', nameAr: 'الهند', nameEn: 'India'),
  (
    key: 'io',
    nameAr: 'إقليم المحيط الهندي البريطاني',
    nameEn: 'British Indian Ocean Territory',
  ),
  (key: 'iq', nameAr: 'العراق', nameEn: 'Iraq'),
  (key: 'ir', nameAr: 'إيران', nameEn: 'Iran (Islamic Republic of)'),
  (key: 'is', nameAr: 'آيسلندا', nameEn: 'Iceland'),
  (key: 'it', nameAr: 'إيطاليا', nameEn: 'Italy'),
  (key: 'je', nameAr: 'جيرزي', nameEn: 'Jersey'),
  (key: 'jm', nameAr: 'جامايكا', nameEn: 'Jamaica'),
  (key: 'jo', nameAr: 'الأردن', nameEn: 'Jordan'),
  (key: 'jp', nameAr: 'اليابان', nameEn: 'Japan'),
  (key: 'ke', nameAr: 'كينيا', nameEn: 'Kenya'),
  (key: 'kg', nameAr: 'قيرغيزستان', nameEn: 'Kyrgyzstan'),
  (key: 'kh', nameAr: 'كمبوديا', nameEn: 'Cambodia'),
  (key: 'ki', nameAr: 'كيريباتي', nameEn: 'Kiribati'),
  (key: 'km', nameAr: 'جزر القمر', nameEn: 'Comoros'),
  (key: 'kn', nameAr: 'سانت كيتس ونيفيس', nameEn: 'Saint Kitts and Nevis'),
  (
    key: 'kp',
    nameAr: 'كوريا الشمالية',
    nameEn: "Korea (Democratic People's Republic of)",
  ),
  (key: 'kr', nameAr: 'كوريا الجنوبية', nameEn: 'Korea, Republic of'),
  (key: 'kw', nameAr: 'الكويت', nameEn: 'Kuwait'),
  (key: 'ky', nameAr: 'جزر كايمان', nameEn: 'Cayman Islands'),
  (key: 'kz', nameAr: 'كازاخستان', nameEn: 'Kazakhstan'),
  (key: 'la', nameAr: 'لاوس', nameEn: "Lao People's Democratic Republic"),
  (key: 'lb', nameAr: 'لبنان', nameEn: 'Lebanon'),
  (key: 'lc', nameAr: 'سانت لوسيا', nameEn: 'Saint Lucia'),
  (key: 'li', nameAr: 'ليختنشتاين', nameEn: 'Liechtenstein'),
  (key: 'lk', nameAr: 'سريلانكا', nameEn: 'Sri Lanka'),
  (key: 'lr', nameAr: 'ليبيريا', nameEn: 'Liberia'),
  (key: 'ls', nameAr: 'ليسوتو', nameEn: 'Lesotho'),
  (key: 'lt', nameAr: 'ليتوانيا', nameEn: 'Lithuania'),
  (key: 'lu', nameAr: 'لوكسمبورغ', nameEn: 'Luxembourg'),
  (key: 'lv', nameAr: 'لاتفيا', nameEn: 'Latvia'),
  (key: 'ly', nameAr: 'ليبيا', nameEn: 'Libya'),
  (key: 'ma', nameAr: 'المغرب', nameEn: 'Morocco'),
  (key: 'mc', nameAr: 'موناكو', nameEn: 'Monaco'),
  (key: 'md', nameAr: 'مولدوفا', nameEn: 'Moldova, Republic of'),
  (key: 'me', nameAr: 'الجبل الأسود', nameEn: 'Montenegro'),
  (key: 'mf', nameAr: 'سان مارتن', nameEn: 'Saint Martin (French part)'),
  (key: 'mg', nameAr: 'مدغشقر', nameEn: 'Madagascar'),
  (key: 'mh', nameAr: 'جزر مارشال', nameEn: 'Marshall Islands'),
  (key: 'mk', nameAr: 'مقدونيا الشمالية', nameEn: 'North Macedonia'),
  (key: 'ml', nameAr: 'مالي', nameEn: 'Mali'),
  (key: 'mm', nameAr: 'ميانمار', nameEn: 'Myanmar'),
  (key: 'mn', nameAr: 'منغوليا', nameEn: 'Mongolia'),
  (key: 'mo', nameAr: 'ماكاو', nameEn: 'Macao'),
  (
    key: 'mp',
    nameAr: 'جزر ماريانا الشمالية',
    nameEn: 'Northern Mariana Islands',
  ),
  (key: 'mq', nameAr: 'مارتينيك', nameEn: 'Martinique'),
  (key: 'mr', nameAr: 'موريتانيا', nameEn: 'Mauritania'),
  (key: 'ms', nameAr: 'مونتسرات', nameEn: 'Montserrat'),
  (key: 'mt', nameAr: 'مالطا', nameEn: 'Malta'),
  (key: 'mu', nameAr: 'موريشيوس', nameEn: 'Mauritius'),
  (key: 'mv', nameAr: 'جزر المالديف', nameEn: 'Maldives'),
  (key: 'mw', nameAr: 'مالاوي', nameEn: 'Malawi'),
  (key: 'mx', nameAr: 'المكسيك', nameEn: 'Mexico'),
  (key: 'my', nameAr: 'ماليزيا', nameEn: 'Malaysia'),
  (key: 'mz', nameAr: 'موزمبيق', nameEn: 'Mozambique'),
  (key: 'na', nameAr: 'ناميبيا', nameEn: 'Namibia'),
  (key: 'nc', nameAr: 'كاليدونيا الجديدة', nameEn: 'New Caledonia'),
  (key: 'ne', nameAr: 'النيجر', nameEn: 'Niger'),
  (key: 'nf', nameAr: 'جزيرة نورفولك', nameEn: 'Norfolk Island'),
  (key: 'ng', nameAr: 'نيجيريا', nameEn: 'Nigeria'),
  (key: 'ni', nameAr: 'نيكاراغوا', nameEn: 'Nicaragua'),
  (key: 'nl', nameAr: 'هولندا', nameEn: 'Netherlands'),
  (key: 'no', nameAr: 'النرويج', nameEn: 'Norway'),
  (key: 'np', nameAr: 'نيبال', nameEn: 'Nepal'),
  (key: 'nr', nameAr: 'ناورو', nameEn: 'Nauru'),
  (key: 'nu', nameAr: 'نيوي', nameEn: 'Niue'),
  (key: 'nz', nameAr: 'نيوزيلندا', nameEn: 'New Zealand'),
  (key: 'om', nameAr: 'عُمان', nameEn: 'Oman'),
  (key: 'pa', nameAr: 'بنما', nameEn: 'Panama'),
  (key: 'pe', nameAr: 'بيرو', nameEn: 'Peru'),
  (key: 'pf', nameAr: 'بولينيزيا الفرنسية', nameEn: 'French Polynesia'),
  (key: 'pg', nameAr: 'بابوا غينيا الجديدة', nameEn: 'Papua New Guinea'),
  (key: 'ph', nameAr: 'الفلبين', nameEn: 'Philippines'),
  (key: 'pk', nameAr: 'باكستان', nameEn: 'Pakistan'),
  (key: 'pl', nameAr: 'بولندا', nameEn: 'Poland'),
  (key: 'pm', nameAr: 'سان بيير وميكلون', nameEn: 'Saint Pierre and Miquelon'),
  (key: 'pn', nameAr: 'جزر بيتكيرن', nameEn: 'Pitcairn'),
  (key: 'pr', nameAr: 'بورتوريكو', nameEn: 'Puerto Rico'),
  (key: 'ps', nameAr: 'دولة فلسطين', nameEn: 'State of Palestine'),
  (key: 'pt', nameAr: 'البرتغال', nameEn: 'Portugal'),
  (key: 'pw', nameAr: 'بالاو', nameEn: 'Palau'),
  (key: 'py', nameAr: 'باراغواي', nameEn: 'Paraguay'),
  (key: 'qa', nameAr: 'قطر', nameEn: 'Qatar'),
  (key: 're', nameAr: 'ريونيون', nameEn: 'Réunion'),
  (key: 'ro', nameAr: 'رومانيا', nameEn: 'Romania'),
  (key: 'rs', nameAr: 'صربيا', nameEn: 'Serbia'),
  (key: 'ru', nameAr: 'روسيا', nameEn: 'Russian Federation'),
  (key: 'rw', nameAr: 'رواندا', nameEn: 'Rwanda'),
  (key: 'sa', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia'),
  (key: 'sb', nameAr: 'جزر سليمان', nameEn: 'Solomon Islands'),
  (key: 'sc', nameAr: 'سيشل', nameEn: 'Seychelles'),
  (key: 'sd', nameAr: 'السودان', nameEn: 'Sudan'),
  (key: 'se', nameAr: 'السويد', nameEn: 'Sweden'),
  (key: 'sg', nameAr: 'سنغافورة', nameEn: 'Singapore'),
  (
    key: 'sh',
    nameAr: 'سانت هيلينا',
    nameEn: 'Saint Helena, Ascension and Tristan da Cunha',
  ),
  (key: 'si', nameAr: 'سلوفينيا', nameEn: 'Slovenia'),
  (key: 'sj', nameAr: 'سفالبارد ويان ماين', nameEn: 'Svalbard and Jan Mayen'),
  (key: 'sk', nameAr: 'سلوفاكيا', nameEn: 'Slovakia'),
  (key: 'sl', nameAr: 'سيراليون', nameEn: 'Sierra Leone'),
  (key: 'sm', nameAr: 'سان مارينو', nameEn: 'San Marino'),
  (key: 'sn', nameAr: 'السنغال', nameEn: 'Senegal'),
  (key: 'so', nameAr: 'الصومال', nameEn: 'Somalia'),
  (key: 'sr', nameAr: 'سورينام', nameEn: 'Suriname'),
  (key: 'ss', nameAr: 'جنوب السودان', nameEn: 'South Sudan'),
  (key: 'st', nameAr: 'ساو تومي وبرينسيبي', nameEn: 'Sao Tome and Principe'),
  (key: 'sv', nameAr: 'السلفادور', nameEn: 'El Salvador'),
  (key: 'sx', nameAr: 'سينت مارتن', nameEn: 'Sint Maarten (Dutch part)'),
  (key: 'sy', nameAr: 'سوريا', nameEn: 'Syrian Arab Republic'),
  (key: 'sz', nameAr: 'إسواتيني', nameEn: 'Eswatini'),
  (key: 'tc', nameAr: 'جزر توركس وكايكوس', nameEn: 'Turks and Caicos Islands'),
  (key: 'td', nameAr: 'تشاد', nameEn: 'Chad'),
  (
    key: 'tf',
    nameAr: 'الأقاليم الجنوبية الفرنسية',
    nameEn: 'French Southern Territories',
  ),
  (key: 'tg', nameAr: 'توغو', nameEn: 'Togo'),
  (key: 'th', nameAr: 'تايلاند', nameEn: 'Thailand'),
  (key: 'tj', nameAr: 'طاجيكستان', nameEn: 'Tajikistan'),
  (key: 'tk', nameAr: 'توكيلاو', nameEn: 'Tokelau'),
  (key: 'tl', nameAr: 'تيمور الشرقية', nameEn: 'Timor-Leste'),
  (key: 'tm', nameAr: 'تركمانستان', nameEn: 'Turkmenistan'),
  (key: 'tn', nameAr: 'تونس', nameEn: 'Tunisia'),
  (key: 'to', nameAr: 'تونغا', nameEn: 'Tonga'),
  (key: 'tr', nameAr: 'تركيا', nameEn: 'Türkiye'),
  (key: 'tt', nameAr: 'ترينيداد وتوباغو', nameEn: 'Trinidad and Tobago'),
  (key: 'tv', nameAr: 'توفالو', nameEn: 'Tuvalu'),
  (key: 'tw', nameAr: 'تايوان', nameEn: 'Taiwan, Province of China'),
  (key: 'tz', nameAr: 'تنزانيا', nameEn: 'Tanzania, United Republic of'),
  (key: 'ua', nameAr: 'أوكرانيا', nameEn: 'Ukraine'),
  (key: 'ug', nameAr: 'أوغندا', nameEn: 'Uganda'),
  (
    key: 'um',
    nameAr: 'جزر الولايات المتحدة النائية الصغيرة',
    nameEn: 'United States Minor Outlying Islands',
  ),
  (
    key: 'us',
    nameAr: 'الولايات المتحدة الأمريكية',
    nameEn: 'United States of America',
  ),
  (key: 'uy', nameAr: 'أوروغواي', nameEn: 'Uruguay'),
  (key: 'uz', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan'),
  (key: 'va', nameAr: 'الكرسي الرسولي', nameEn: 'Holy See'),
  (
    key: 'vc',
    nameAr: 'سانت فنسنت والغرينادين',
    nameEn: 'Saint Vincent and the Grenadines',
  ),
  (key: 've', nameAr: 'فنزويلا', nameEn: 'Venezuela (Bolivarian Republic of)'),
  (
    key: 'vg',
    nameAr: 'جزر العذراء البريطانية',
    nameEn: 'Virgin Islands (British)',
  ),
  (key: 'vi', nameAr: 'جزر العذراء الأمريكية', nameEn: 'Virgin Islands (U.S.)'),
  (key: 'vn', nameAr: 'فيتنام', nameEn: 'Viet Nam'),
  (key: 'vu', nameAr: 'فانواتو', nameEn: 'Vanuatu'),
  (key: 'wf', nameAr: 'واليس وفوتونا', nameEn: 'Wallis and Futuna'),
  (key: 'ws', nameAr: 'ساموا', nameEn: 'Samoa'),
  (key: 'ye', nameAr: 'اليمن', nameEn: 'Yemen'),
  (key: 'yt', nameAr: 'مايوت', nameEn: 'Mayotte'),
  (key: 'za', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa'),
  (key: 'zm', nameAr: 'زامبيا', nameEn: 'Zambia'),
  (key: 'zw', nameAr: 'زيمبابوي', nameEn: 'Zimbabwe'),
];

/// Database key for the State of Palestine (the default document country).
const String palestineCountryKey = 'ps';

/// Returns the canonical seed/display ordering for countries:
///
/// 1. The State of Palestine (`ps`) is pinned first for convenient selection.
/// 2. All remaining entries follow, ordered deterministically by English
///    display name.
///
/// The returned order is stable and is what callers should use to assign
/// `sort_order`.
List<CountrySeed> orderedCountrySeedData() {
  final List<CountrySeed> rest =
      kCountrySeedData.where((c) => c.key != palestineCountryKey).toList()
        ..sort((a, b) => a.nameEn.compareTo(b.nameEn));
  final CountrySeed palestine = kCountrySeedData.firstWhere(
    (c) => c.key == palestineCountryKey,
  );
  return <CountrySeed>[palestine, ...rest];
}
